### ISSUE TITLE
[adm] Can not link modal

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/postcssify#29]
When installing modal from npm, it works perfectly. But when I link exactly same version, but from local, it throws that error:

```
nikoloza@nika ~/www/abu-dhabi-media  [19:54:38]
> $ npm link @vigour-io/play-modal
/Users/nikoloza/www/abu-dhabi-media/node_modules/@vigour-io/play-modal -> /Users/nikoloza/.nvm/versions/node/v4.2.3/lib/node_modules/@vigour-io/play-modal -> /Users/nikoloza/www/play/modal

nikoloza@nika ~/www/abu-dhabi-media  [19:54:49]
> $ npm run dev

> abu-dhabi-media@1.0.92 dev /Users/nikoloza/www/abu-dhabi-media
> budo ./platform/main.js --css bundle.css --live --pushstate -- -r ./package.json:package.json

[0001] info  Server running at http://192.168.1.59:9966/ (connect)
[0001] info  LiveReload running on 35729
[0002] info  output: bundle.css (postcssify)
[0012] info  updated: bundle.css (postcssify)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
[0012] 57ms        66KB GET    200 /bundle.css
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
AST -> Result + plugins TypeError: Cannot read property 'toResult' of undefined
    at /Users/nikoloza/www/play/modal/node_modules/postcssify/bundle.js:188:28
    at process._tickCallback (node.js:368:9)
[0013] 12.6s      3.1MB (browserify)
[0014] info  updated: bundle.css (postcssify)
[0014] 5ms         66KB GET    200 /bundle.css
[0014] 2ms         39KB GET    200 /bundle.css
```

PS: **adm** on branch `feature/local-imports` and **postcssify**: `feature/transform`

**Comment by nikoloza** [comment]
not sure whom to assign, @youzi or @shawninder

**Comment by nikoloza** [comment]
Oh it works, only needed `postcssify` to link into modal as well.

**Comment by nikoloza** [comment]
@shawninder why do we use `postcssify` in every package locally instead of making global one?

**Comment by shawninder** [comment]
so that it doesn't run on modules that don't need it (the majority of modules), which would slow it down considerably. Also just in principle, to follow the browserify convention..
